version: '3.4'

services:
  klockan-frontend:
    container_name: frontend-container
    build: .
    image: klockan-frontend:v1
    ports:
      - 80:80
    networks:
      - klockan-network

networks:
  klockan-network:
    driver: bridge