name: Build and Push to Docker Hub

on:
  push:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker-compose build
      - name: Tagin frontend with version
        run: docker tag klockan-frontend:v1 klockan/frontend:v${{ secrets.FRONTEND_MAJOR }}.${{ secrets.FRONTEND_MINOR }}.${{ github.sha }}
      - name: Push to docker hub
        run: docker push klockan/frontend:v${{ secrets.FRONTEND_MAJOR }}.${{ secrets.FRONTEND_MINOR }}.${{ github.sha }}
      - name: Tagin frontend with tag latest
        run: docker tag klockan-frontend:v1 klockan/frontend:latest
      - name: Push to docker hub
        run: docker push klockan/frontend:latest
