# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build

             

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
      - name: Login Dockerhub
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
            MAJOR_TAG: ${{ secrets.MAJOR_TAG }}
            MINOR_TAG: ${{ secrets.MINOR_TAG }}
      
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: klockan-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ secrets.MAJOR_TAG }} ${{ secrets.MINOR_TAG }}
          labels: nolabe
