name: Deploy

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull image
        run: sudo docker pull klockan/frontend:latest
      - name: Run
        run: sudo docker-compose build
      
